import type { Metadata } from "next";
import Link from "next/link";
import { searchQuran } from "@/lib/quran/search";
import { ArabicText } from "@/components/islamic/arabic-text";
export const metadata: Metadata = { title: "Rechercher dans le Coran", robots: { index: false } };
export default async function SearchPage({ searchParams }: { searchParams: Promise<{ q?: string; page?: string }> }) {
  const params = await searchParams;
  const q = typeof params.q === "string" ? params.q.trim().slice(0,120) : "";
  const data = searchQuran(q, Number(params.page) || 1);
  return <div className="premium-container max-w-4xl py-14"><Link href="/coran" className="text-sm text-primary underline">Le Coran</Link><h1 className="mt-5 font-display text-4xl">Retrouver un verset</h1><p className="mt-4 text-muted">Par mots arabes, mots de la traduction du sens de Muhammad Hamidullah ou référence : 2:255. Tous les mots saisis doivent figurer dans le même verset.</p><form className="mt-6 flex flex-wrap gap-3" action="/coran/recherche" method="get"><label htmlFor="quran-search" className="sr-only">Mots ou référence du verset</label><input id="quran-search" name="q" defaultValue={q} minLength={2} maxLength={120} required placeholder="Ex. miséricorde ou 2:255" className="min-h-12 min-w-0 flex-1 rounded-xl border border-border bg-surface px-4" /><button className="min-h-12 rounded-xl bg-primary px-5 font-semibold text-primary-foreground">Rechercher</button></form>{q && <p className="mt-5 text-sm" role="status">{data.total} résultat{data.total > 1 ? "s" : ""}{q.length < 2 ? " · saisissez au moins deux caractères." : ""}</p>}<ol className="mt-6 space-y-5">{data.results.map(v => <li key={`${v.chapter}:${v.number}`} className="rounded-2xl border border-accent/25 bg-surface p-5"><Link href={`/coran/${v.chapter}#verset-${v.number}`} className="font-semibold text-primary underline">Sourate {v.chapter} · verset {v.number}</Link><ArabicText as="p" variant="quran" className="mt-5 text-2xl leading-loose">{v.arabic}</ArabicText><p lang="fr" className="mt-4 text-base leading-8">{v.french}</p></li>)}</ol>{data.total > 20 && <nav aria-label="Pages de résultats" className="mt-8 flex justify-between gap-4">{data.page > 1 ? <Link href={`/coran/recherche?q=${encodeURIComponent(q)}&page=${data.page-1}`}>Précédente</Link> : <span />}<span className="text-sm">{data.page} / {Math.ceil(data.total / 20)}</span>{data.page*20 < data.total && <Link href={`/coran/recherche?q=${encodeURIComponent(q)}&page=${data.page+1}`}>Suivante</Link>}</nav>}</div>;
}
